gauge:
  build: .
  volumes:
    - .:/app
  entrypoint: gauge

  links:
    - chrome

chrome:
  image: selenium/standalone-chrome-debug:3.4.0-einsteinium
  ports:
    - "4444:4444"
    - "5900:5900"
  stdin_open: true
  tty: true
